name: system_design_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  webview_flutter: ^4.0.7




  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: ^7.3.2
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - http://127.0.0.1:5500/assets/maplibre/index3.html
