name: Lint check with reviewdog

on:
  pull_request:
    branches:
        - main

jobs:
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2.12.0
              with:
                flutter-version: '3.1.3'
            - run: flutter pub get
            - name: setup reviewdog
              uses: reviewdog/action-setup@v1
            - name: run reviewdog
              env:
                REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                reviewdog -conf=./.reviewdog.yml reporter=github-pr-review -filter-mode=file

